# https://travis-ci.org/orbingol/NURBS-Python

language: python

python:
  - "2.7"
  - "3.6"
  - "pypy"

# install required packages
install:
  - pip install pytest
  - pip install codecov

# install package and run tests
script: "python setup.py develop && pytest"

# require the branch name to be master
if: branch = master

# call at the end of CI build
after_success:
  - codecov
